### PR TITLE
Adding auth

### PR DESCRIPTION
**Pull request by b0llu**
## What to check
- [ ] src/Context/Auth.context.js

## What not to check 
- [ ] Do Not Check Any Other Files

live Preview,
https://stormmedia.netlify.app/home

### CODE REVIEW

**Review by ParthParolekar — APPROVED** [review]
A suggestion: call the login function just after the user signs up successfully so they don't have to log in separately. Everything else looks great

**Review by ParthParolekar — COMMENTED** [review]
Also, add some margin at the bottom or keep the vertical scroll visible. I had to zoom out to click the signup button

**Comment by b0llu** [comment]
> Also, add some margin at the bottom or keep the vertical scroll visible. I had to zoom out to click the signup button

I have yet to work on responsiveness for smaller screens. Will work on it soon

**Review by ApurvaSawant11 — APPROVED** [review]
Looks good to me! Just had a suggestion: reduce the font size of left sidebar.  It looks way bigger than the rest of the content.

**Pull request merged**
